name: Docker Image CI

on:
  workflow_dispatch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: login to docker hub
      uses: docker/login-action@v3.3.0
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Build Docker image
      run: docker build -t xedose/springboot-app .

    - name: Push Docker image
      run: docker push xedose/springboot-app
